data:
  dataset: ModelNet10
  root: data
  num_points: 2048
  num_classes: 10
  
  transforms:
    jitter_mean: 0.0
    jitter_std: 0.02

train:
  lr: 1E-3
  momentum: 0.9
  weight_decay: 1E-4
  epochs: 1
  batch_size: 32
  num_prefetch: 8
  log_interval: 10

device: cuda
